// VueVsReact/react/src/Ref/Ref.js
/* With useRef hook, you can create a "ref object" for accessing DOM.
 The object's current property contains reference for the DOM.
 */

import React, { useRef } from "react";

function MyComponent() {
  const target = useRef(null);

  const handleClick = () => {
    console.log(target.current);
  };

  return (
    <>
      <div ref={target}>...</div>
      <button onClick={handleClick}>Click me</button>
    </>
  );
}

export default MyComponent;

// VueVsReact/vue/src/Ref/Ref.vue
<!--- Vue.js way

In Vue.js, ref gives you direct access to the DOM. --->

<template>
  <div>
    <div ref="foo">...</div>
    <button @click="handleClick">Click me</button>
  </div>
</template>

<script>
export default {
  methods: {
    handleClick() {
      console.log(this.$refs.foo);
    },
  },
};
</script>
